/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package institutemanagementsystem;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Basanta
 */
public class DisplayCourse extends javax.swing.JPanel {

    /**
     * Creates new form DisplayCourse
     */
    DefaultTableModel dtm ;
    public DisplayCourse() {
        initComponents();
       dtm = (DefaultTableModel)jTable1.getModel();//typecasting gareko
        dtm.setRowCount(0);
        Statement st = DBConnection.statementObject();
        String sql = "SELECT*FROM course";
        try{
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                dtm.addRow(new Object[]{rs.getInt("cid"),rs.getString("title"),rs.getString("price"),rs.getString("duration")});//object ko arrey
            }
            System.out.println("Data Displayed");
        }
        catch(Exception e){
            System.out.println("Data not displayed");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cid", "Title", "Price", "Duration"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int noOfSelectedRow = jTable1.getSelectedRowCount();
        if(noOfSelectedRow == 1){
            int rowNo = jTable1.getSelectedRow();
            Object cid = jTable1.getValueAt(rowNo,0);
            Statement st = DBConnection.statementObject();
            int confirmDelete = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete?","Alert",JOptionPane.YES_NO_OPTION);
           if(confirmDelete == 0){
            String sql = "DELETE FROM course WHERE cid = "+cid;
            try{
                st.executeUpdate(sql);
                dtm.removeRow(rowNo);
                JOptionPane.showMessageDialog(this,"Deleted Successfully");
                System.out.println("data deleted");
            }
            catch(Exception e){
                System.out.println("data not deleted");
            }
           }
        }else{
            JOptionPane.showMessageDialog(this,"Please select a row to delete");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String SearchItem = jTextField1.getText();
        dtm.setRowCount(0);
        Statement st = DBConnection.statementObject();
        String sql = "SELECT * FROM course WHERE CONCAT(title,price,duration)LIKE '%"+SearchItem+"%'";
        try{
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                dtm.addRow(new Object[]{rs.getInt("cid"),rs.getString("title"),rs.getString("price"),rs.getString("duration")});//object ko arrey
            }
            System.out.println("Data Searched");
        }
        catch(Exception e){
            System.out.println("Data not Searched");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int noOfSelectedRow = jTable1.getSelectedRowCount();
        if(noOfSelectedRow == 1){
            int rowNo = jTable1.getSelectedRow();
            Object cid = jTable1.getValueAt(rowNo,0);
            MainFrame.changepanel(new EditCourse(cid));
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
